### PR TITLE
Improved skewness & airFoil2D compatibility

### PR DESCRIPTION
**Pull request by hrobeers**
Note: I'm still in progress of benchmarking and validating.

These changes do:

1. Lower maximum skewness
2. Improve BL refinement
3. Fix compatibility with airFoil2D tutorial

The images below illustrate the improvements.
Note that the resolution is kept identical, this has no impact on skewness but is important when comparing BL refinement.

## Full mesh skewness
Original:
Full mesh original
Improved:
Full mesh improved

## Zoomed skewness
Original:
Full mesh original
Improved:
Full mesh improved

## BL refinement (same number of cells)
Original:
Full mesh original
Improved:
Full mesh improved

### CODE REVIEW

**Comment by hrobeers** [comment]
@ehsanMa86 I'm wondering what you used this mesh for, laminar flow?

I'm far from a mesh independent solution using this mesh for the NACA0012 SA validation case https://turbmodels.larc.nasa.gov/naca0012_val.html

Without these improvements it's not even converging.

I will try to get this mesh closer to the NASA mesh.

**Comment by ehsanMa86** [comment]
@hrobeers Wow, this looks great! I merged your changes to the repository. Thanks for your contribution. 

I didn't use this mesh for the CFD test cases. So I am short in answering to the question of the convergence of solution.

**Comment by hrobeers** [comment]
You're welcome, thanks for the great starting point ;)

I'm getting closer to a scalable and validated mesh, updates will follow later.

**Comment by ehsanMa86** [comment]
Thanks for improving it. It makes a huge difference.

**Pull request merged**
